[package]
name = "awqat"
readme = "README.md"
license = "GPL-3.0-only"
version = "0.1.4"
edition = "2021"

[dependencies]
scraper = "0.15.0"
ureq = "2.6.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
